// Get slug as argument
const slug = process.argv[2];

// required to write files
const fs = require('fs')

// Required to run HTTP requests (usually handled by browser)
global.XMLHttpRequest = require('xhr2');

// Link to compiled Elm code main.js and run it
var Elm = require("./main").Elm;
var main = Elm.Main.init({ flags: slug });

// Get data from the elm app
main.ports.stdout.subscribe(files => {
    files.forEach(file => {
        // Write files generated by Elm
        console.log("Writing file " + file.path);
        fs.writeFile(file.path, file.file, err => {
            if (err) {
                console.error(err);
                return;
            }
        });
    });
});
